
import javafx.fxml.FXML;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.*;
import javafx.scene.control.*;

import java.net.URL;
import java.util.ResourceBundle;

/**
 * This class will be used as the controller of the game board scene. It uses the MVC design and will work with the fxml
 * scene file (view) and the Board Model class (model) to produce a working tic tac toe game for the user.
 *
 * @author Teagen Kiel
 */
public class BoardController {


    /**
     * The model that will be used to store data for the controller and work with the view.
     */
    private BoardModel model;

    /**
     * The variable to represent the grid pane that the game is played on.
     */
    @FXML
    public GridPane gameGrid;

    /**
     * The variable which will represent the label which displays the game info to the user.
     */
    @FXML
    public Label gameLabel;


    /**
     * This method will set the players for the game. These player variables will hold the specific type of player
     * needed when the user clicks whichever game will be played.
     *
     * @param player1 the first player specifying type desired
     * @param player2 the second player with type desired
     */
    public void setPlayers(Player player1, Player player2) {

        this.model = new BoardModel(player1, player2);
        gameLabel.setText(model.getCurrentPlayer().getName() + "'s turn");
        this.model.setGameRunning(true);

    }

    /**
     * This method is the event handler for whenever the user clicks on a grid node of the playing field.
     * It will use the player type stored in the model to make a move based on which node is clicked. It will
     * also store data in the model for data pertaining to the game (move count, last move made, etc.)
     *
     * @param e the mouse event generated by the click
     */
    @FXML
    public void gridClicked(MouseEvent e) {

        if (model.isGameRunning()) {
            int[] selectedGrid;
            int[] gridClick = {0, 0};

            Label clickedLabel = (Label) e.getSource();
            Pane clickedPane = (Pane) clickedLabel.getParent();
            Integer rowIndex = GridPane.getRowIndex(clickedPane);
            Integer columnIndex = GridPane.getColumnIndex(clickedPane);

            //column and row indexes of zero are signified by null, so these statements will convert the null return
            //back into zero.
            if (rowIndex == null && columnIndex == null) {
                gridClick[0] = 0;
                gridClick[1] = 0;
            } else if (rowIndex == null) {
                gridClick[0] = 0;
                gridClick[1] = columnIndex;
            } else if (columnIndex == null) {
                gridClick[0] = rowIndex;
                gridClick[1] = 0;
            } else {
                gridClick[0] = rowIndex;
                gridClick[1] = columnIndex;
            }

            model.getCurrentPlayer().setLastGridClick(gridClick);

            //polymorphically move based on the type of player stored
            selectedGrid = model.getCurrentPlayer().move(model.getOtherPlayer());

            //Set text of the node that was clicked
            Pane selectedPane = (Pane) (gameGrid.getChildren().get(selectedGrid[0] * 3 + selectedGrid[1]));
            Label selectedLabel = (Label) selectedPane.getChildren().get(0);
            selectedLabel.setText(model.getCurrentPlayer().getMoveLetter());

            model.changePlayers();
            gameLabel.setText(model.getCurrentPlayer().getName() + "'s turn");

        }

        if (model.getOtherPlayer().checkWin()) {

            gameLabel.setText(model.getOtherPlayer().getName() + " wins!");

            model.setGameRunning(false);
        }

        if (model.getGameCount() == 8 && model.isGameRunning()) {

            gameLabel.setText("Cat's game!");
            model.setGameRunning(false);
        }


        model.setGameCount(model.getGameCount() + 1);


    }

}
